services:

  api_trades:
    image: aeor06/trading_future:api_trades
    build:
      context: ./api_trades
    env_file:
      - ./api_trades/.env
    ports:
      - "3010:3000"
    restart: unless-stopped
    networks: [ trading_net ]
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  detect_opportunity:
    image: aeor06/trading_future:detect_opportunity
    build:
      context: ./detect_oportunity
    env_file:
      - ./detect_oportunity/.env
    restart: unless-stopped
    depends_on: [ api_trades ]
    networks: [ trading_net ]
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  detect_oportunity_vwap:
    image: aeor06/trading_future:detect_oportunity_vwap
    build:
      context: ./detect_oportunity_vwap
    env_file:
      - ./detect_oportunity_vwap/.env
    restart: unless-stopped
    depends_on: [ api_trades ]
    networks: [ trading_net ]
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  front_market:
    image: aeor06/trading_future:front_market
    build:
      context: ./front_market
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on: [ detect_opportunity, api_trades ]
    networks: [ trading_net ]
    logging:
      options:
        max-size: "10m"
        max-file: "5"

networks:
  trading_net:
    driver: bridge
